# https://docs.github.com/en/actions/learn-github-actions/contexts
name: Output Information
on: [workflow_dispatch]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        run: echo "${{ toJson(github) }}"
